### ISSUE TITLE
State: No map detected in screenshot.

### ISSUE THREAD

**Issue by FwSchultz** [CommonParrot/HLLMapCapture#1]
Hi, I have set everything as you wanted in the settings. but it still doesn't recognise any card ingame when you press M. Map is completely zoomed out.

I tested it with full screen in the window and with full screen.

**Comment by FwSchultz** [comment]
could it be that you have not yet released version 1.0.1?

**Comment by DerDreher** [comment]
Look in your Screenshot folder. The maps are available for me, even on the FTP. The status display in the programme is a little confusing 😕

**Comment by CommonParrot** [comment]
Yeah I released the v1.0.1 version just now. It was only a small change to the status message, 
which should make it less confusing. But there are no changes to the detection itself.

There could still be edge cases where it doesn't work, so if your detection really fails,
you can share a screenshot of the whole screen here. Then I can reproduce the bug
and improve the detection.
Also if you play the game on a screen which is not the primary screen for windows,
the tool will fail because it only captures the primary screen per default.

**Comment by FwSchultz** [comment]
ah now it works. the problem was really that i had the programme on the 2nd monitor and not on the monitor where hll was running.

thanks

**Comment by CommonParrot** [comment]
Just for clarification: HLLMapCapture can run on any monitor, HLL itself has to run on the primary one.
Problem probably was just the confusing UI.
