### ISSUE TITLE
No map detected in screenshot ... on many users

### ISSUE THREAD

**Issue by DerDreher** [CommonParrot/HLLMapCapture#3]
Hey CommonParrot,

since the second last HLL patch, the maps are no longer detected, especially at FullHD resolutions. I'll send you a few screenshots to test.

Greetings Rambo_GT

![image](https://github.com/CommonParrot/HLLMapCapture/assets/32548142/67b18a2b-975f-4b87-9592-487554689df8)

**Comment by DerDreher** [comment]
![image 1](https://github.com/CommonParrot/HLLMapCapture/assets/32548142/07fa60ac-5163-4985-a47e-df33612b62ad)

**Comment by DerDreher** [comment]
![20240528115345_1 1](https://github.com/CommonParrot/HLLMapCapture/assets/32548142/0fe570a1-cbf3-4e4c-9e76-7fb6e3149519)

**Comment by CommonParrot** [comment]
Hi Rambo,

it seems like the bottom border of the map looks slightly different now.
Your screenshots aren't detected on my end either.
I have a 1080p screenshot which I use for testing and that still works:

![686810_20240307120115_1](https://github.com/CommonParrot/HLLMapCapture/assets/25479515/92011403-a180-45fb-b0ad-9bbb780874d5)

I have to check if it is still the same in my game or if the pronounced white of the bottom border, of the map has really changed.
I didn't expect them to change how the maps borders look, since it's a small detail and a good design.

Maybe this bug-fix in Update 15 has something to do with that:
" Practice Range

     The map is unaligned to the out-of-bounds parameters of the tactical map by 10m"
     
Maybe they did something to realign the map in the practice range which affected every map screen in the game.
That would be unfortunate, but is only speculation for now.

Anyway, I need to plan in time to check this out in-game and probably rework the detection too,
so it might take until the middle of June.
It would also be helpful to know under which circumstances the detection breaks and for which resolutions
the bottom border of the maps was changed. 
Screenshots from maps before and after the patch, for different resolutions would be perfect.

**Comment by CommonParrot** [comment]
Fixed with commit e0b1228
